### ISSUE TITLE
fails to build with ghc-9.6 stackage nightly

### ISSUE THREAD

**Issue by juhp** [clinty/debian-haskell#5]
```
       Building library for debian-4.0.4..                                                                              [420/157179]
       [ 8 of 39] Compiling Debian.Control.ByteString                                                                               
                                                                                                                                    
       /var/stackage/work/unpack-dir/unpacked/debian-4.0.4-39f77553cd21a2cf72f26ecec7d66a190ec8fa2cb055126e2b6743dc54295f23/src/Debi
an/Control/ByteString.hs:201:10: error: [GHC-76037]                                                                                 
           Not in scope: type constructor or class ‘MonadPlus’                                                                      
           |                                                                                                                        
       201 | instance MonadPlus (Parser state) where                                                                                
           |          ^^^^^^^^^                                                                                                     
       [17 of 39] Compiling Debian.Apt.Methods                                                                                      
                                                                                                                                    
       /var/stackage/work/unpack-dir/unpacked/debian-4.0.4-39f77553cd21a2cf72f26ecec7d66a190ec8fa2cb055126e2b6743dc54295f23/src/Debi
an/Apt/Methods.hs:96:15: error: [GHC-88464]                                                                                         
           Variable not in scope:                                                                                                   
             liftM :: (Maybe a0 -> a0) -> IO (Maybe FilePath) -> IO FilePath                                                        
          |                                                                                                                         
       96 |     do  mp <- liftM fromJust (whichMethodPath uri)                                                                      
          |               ^^^^^                                                                                                     
                                                                                                                                    
       /var/stackage/work/unpack-dir/unpacked/debian-4.0.4-39f77553cd21a2cf72f26ecec7d66a190ec8fa2cb055126e2b6743dc54295f23/src/Debi
an/Apt/Methods.hs:224:17: error: [GHC-88464]                                                                                        
           Variable not in scope:                                                                                                   
             liftM :: ([String] -> Status) -> IO [String] -> IO Status
           |                                                                                                                        
       224 | recvStatus mh = liftM parseStatus $ recv mh                                                                            
           |                 ^^^^^                                                                                                  
                                 
       /var/stackage/work/unpack-dir/unpacked/debian-4.0.4-39f77553cd21a2cf72f26ecec7d66a190ec8fa2cb055126e2b6743dc54295f23/src/Debi
an/Apt/Methods.hs:375:23: error: [GHC-88464]
           Variable not in scope: unless :: Bool -> IO () -> IO a1                                                                  
           |                     
       375 |                    do unless (null configItems) (sendCommand' mh (Configuration configItems))
           |                       ^^^^^^
```

**Comment by clinty** [comment]
fixed by https://github.com/clinty/debian-haskell/commit/ce3068530de7168528a598433d74860a87929b28
